
server:
  port: 7001

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:7000/eureka/

spring:
  application:
    name: eurka-server
