
server:
  port: 7000

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:7001/eureka/

spring:
  application:
    name: eurka-server
